# Face Detection


In [17]:
import cv2
import numpy as np

In [18]:
# Load haar cascade for face detection
haar_features=cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [23]:
img=cv2.imread("face.jpg")
# output -> array 
# rows = no of face detected
# col- > coordinate of face (x,y,width,height)

#parameters 
# 1- image
# 2- scaleFactor - how much image is reduced at each step
faces = haar_features.detectMultiScale(img)

print(faces)

[[ 84   2  25  25]
 [132 113  43  43]
 [209  66  48  48]
 [ 54  58  40  40]]


In [20]:
for x,y,w,h in faces:
    # parameters - >( img, (x,y coordinate (top-left)), (x+width, y+height(bottom right)),(colour(B,G,R)),thickness)
    cv2.rectangle(img, (x,y), (x+w, y+h),(0,255,0),2)

In [21]:
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()